services:
  postgres:
    image: postgres:18

    container_name: fleet-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: fleet_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: